### ISSUE TITLE
Run Failed: Invalid Username

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/spotify-to-yaml-action#134]
‘’’
Error: An error occurred while communicating with Spotify's Web API.
Details: Invalid username.
‘’’

Link: https://github.com/flamedfury/metadata-library/actions/runs/6243617257/job/16949286611

hello again Katy 👋

could you help me understand what username this is failing on? ‘spotify-username-‘ or the secret ‘ SPOTIFYUSER’?

As far as I’m aware, nothing has changed since it last run successfully.

**Comment by katydecorah** [comment]
Hey there, @flamedfury! This was a breaking change in v8: https://github.com/katydecorah/spotify-to-yaml-action/releases/tag/v8.0.0

You'll want to replace the inputs for this action with the new pattern, like so:

```yaml
with:
  spotify-username: "you-spotify-username"
  season-names: "season,season,season"
```

(This is annoying and I'm sorry <3)
